[alembic]
script_location = alembic
prepend_sys_path = .
version_path_separator = os

[post_write_hooks]
hooks = black
black.type = file
black.entrypoint = black

[tool.black]
line-length = 88
target-version = ['py311']

[alembic:exclude]
sqlalchemy.url = driver://user:pass@localhost/dbname

[alembic:target_metadata]
sqlalchemy.url = driver://user:pass@localhost/dbname